### ISSUE TITLE
Implement BDI

### ISSUE THREAD

**Issue by brandonros** [Banno/node-sso-formatter#5]
## Summary

Work with ChadK, Chris Gidley, and Nick D to make sure the upcoming BDI SSO works all the way through in UAT.

This will involve getting claims from the node-consumer-sso provider, then redirecting the user to the BDI URL with the appropriate form fields.

Technical docs: https://drive.google.com/drive/u/1/folders/1zfI2j-EDjP_fiB0XxmByPN8Ghi2F0hXg

**Comment by brandonros** [comment]
Blocked by https://github.com/Banno/node-consumer-sso/issues/63

**Comment by ChadKillingsworth** [comment]
This is unblocked now right?

**Comment by brandonros** [comment]
@ChadKillingsworth No. BDI hasn't responded to our second followup about IP whitelisting.

cc @RickRahl

**Comment by RickRahl** [comment]
I'll fire off a third follow-up now.

**Comment by RickRahl** [comment]
Our BDI contact is out all week so I sent it on to their generic support email to see if someone else can help us move forward. I'll let you know if I get a response.

**Comment by ChadKillingsworth** [comment]
@RickRahl Can we escalate this?

**Comment by RickRahl** [comment]
They responded last week that they were working on it. This morning I checked in again and our main contact is back and responded. He gave us a cert to use and said the whitelisting was completed.

@brandonros I'll call him to get the cert password, let me know if you have anything else you need to be able to test.

**Comment by brandonros** [comment]
@ChadKillingsworth I have no idea how I'm supposed to use this HTTPS certificate with node-sso-formatter. Loading https://dev2ssl.businessdatainc.com/ClockmakersFCU/SSOLogonRequest.do in my browser asks me to present a certificate... which means node-sso-formatter is going to need to do that programatically. Is there another SSO that you are aware of that we have done this before?

**Comment by ChadKillingsworth** [comment]
@brandonros I think it's this: https://stackoverflow.com/a/23578373/1211524

@RickRahl we need to know if this cert is shared across all FIs or if each FI would use it's own client certificate.

**Comment by brandonros** [comment]
@ChadKillingsworth I get what the the cert will be. What will the key be?

**Comment by ChadKillingsworth** [comment]
Did they provide the cert as a PEM with both parts in it?

Otherwise, I'm not exactly sure.

**Comment by RickRahl** [comment]
They provided a .p12 file which contains client/server certificates.

**Comment by brandonros** [comment]
@ChadKillingsworth is that enough, or do we need a key?

cc @landonlewis

**Comment by ChadKillingsworth** [comment]
That's enough. We can use Open SSL to split that into a pem encoded cert and key.

**Comment by brandonros** [comment]
Assigning to @mpecarina and @eheikes

**Comment by brandonros** [comment]
@ChadKillingsworth How will a certificate/key work if we're SSOing to *their* URL from the client that requires the client present the certificate?

I never make a request to BDI from `node-sso-formatter`. I build a HTML <form> that the client uses to POST.

Sounds like we've got a majorly overlooked design problem that we're just discovering now (again, lol)

Regardless, I ran

`openssl pkcs12 -in path.p12 -out newfile.key.pem -nocerts -nodes`
`openssl pkcs12 -in path.p12 -out newfile.crt.pem -clcerts -nokeys`

I have the key + certificate to put into Vault. I will have ops put it into Vault at: `secret/sso/bdi-key` and `secret/sso/bdi-certificate`

**Comment by ChadKillingsworth** [comment]
It's all there - just gotta read the spec: https://drive.google.com/drive/u/0/folders/1zfI2j-EDjP_fiB0XxmByPN8Ghi2F0hXg

**Comment by brandonros** [comment]
Engaging the vendor on why we get `SSONoEmail` as a response. But, we are very close.

**Comment by brandonros** [comment]
The vendor fixed their test/QA instance and we had a successful SSO.
